### PR TITLE
Problem: Need CSV data from Google Sheets

### LINKED ISSUE #2: Import google spreadsheet to Python Jupyter Notebook
Check out:

https://developers.google.com/sheets/api/quickstart/python?authuser=1

### PR DESCRIPTION
**Pull request by julianpistorius**
Solution: Use the CSV export URL to download the data.

Fixes #2

### CODE REVIEW

**Comment by agladstein** [comment]
Good job!

**Comment by agladstein** [comment]
@julianpistorius 
Adding in those packages creates dependencies. With binder it works I guess because of docker magic. But, it seemed like a bad idea to develop and push from binder because then you are putting your github username and password on the binder server.
So, for developing locally, we should include install instructions. @nlupugla uses anaconda and I think on a PC.

**Comment by agladstein** [comment]
@julianpistorius 
Also, I got this error when I tried your notebook. 
screen shot 2018-08-12 at 9 11 54 pm

This was with a public view only link.

**Comment by julianpistorius** [comment]
@agladstein - Ah, so the `ts` parameter confused things. You can modify the regex in parse to be more permissive.

**Pull request merged**
